# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run test
  run-build:
    name: Run build
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run build
  sftp-deploy:
    name: SFTP deploy
    needs: run-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run build
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.FTP_USER }}
          server: ${{ secrets.FTP_SERVER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './build/*'
          remote_path: '/var/www/html/test-app'
          args: '-o ConnectTimeout=5'
